### PR TITLE
Simplify tooling, rely only on CloudFormation

### PR DESCRIPTION
**Pull request by alukach**
Given #48 and #53 (along with my personal issues getting this project building locally), I would suggest we abandon `lono` entirely and simply rely on CloudFormation alone.

I have created YAML files to illustrate the build up to this point.  Switching to YAML made it possible to keep the UserData very clean and legible. The downsides are:

* the UserData script is duplicated in the two separate YAML files rather than being written once in the authoritative `src/templates/user_data/Webdigi-Base-VPN-UserData.sh.erb` file
* the instance size options must be duplicated in the two separate YAML files rather than being written once in the authoritative `src/config/lono.rb` file

Finally, out of a small personal desire, I changed the speed options to reflect both the original "Standard/High.Speed/Ultra.High.Speed" and also the machine sizes that they select.  I thought this was important information for an end-user to know.

I'll be moving forward with this YAML script on a personal project.  I'll leave it up to you to decide if you'd like to switch over to use them or not.

p.s. Thanks for this repo in general, it has been very helpful.

### CODE REVIEW

**Comment by alukach** [comment]
A final thought: It may be possible to build in logic using the [`Fn::If`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-conditions.html#intrinsic-function-reference-conditions-if) along with `AWS::NoValue` pseudo parameter to merge the two CloudFormation templates into one, meaning that there would not be any duplication of code between the two.

**Comment by alukach** [comment]
Actually, I think my last commit should do the trick.  **I have not actually had a chance to test this change aside from proving that it validates.**

**Comment by webdigi** [comment]
This looks like a great alternative to lono. Also using the new YAML support for AWS should work well.

When selecting with no key name it shows "Parameter validation failed: parameter value for parameter name KeyName does not exist. Rollback requested by user." Any ideas?

We might have to create two yaml files similar to the two files we have now. One for key name and one without keyname? Let me know if you have any solution to keep it as one file like you have now.

**Comment by alukach** [comment]
> When selecting with no key name it shows "Parameter validation failed: parameter value for parameter name KeyName does not exist. Rollback requested by user." Any ideas?

Ah, yeah, I am also getting that error when testing.  Reading [the docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html#w2ab2c17c15c17c21b5):

> ... if you use the AWS::EC2::KeyPair::KeyName parameter type, AWS CloudFormation validates the input value against users' existing key pair names before it creates any resources, such as Amazon EC2 instances.

So it seems that if we use the `Type: AWS::EC2::KeyPair::KeyName` parameter (which renders the nice dropdown of keynames), the value can not be null.

it feels like we can update the field to be `Type: String` and have the end-user type in the name of their Key (which is not the best experience) or break the templates up into two separate templates (making management of the two a bit more difficult).

What do you think?

**Comment by webdigi** [comment]
Great work. Some more changes and I will commit those shortly & update documentation

**Pull request merged**
